package pl.fejzu.persistence.sync;

public enum SyncPacketType {
    PLAYER_FULL_SYNC,
    PLAYER_FIELD_SYNC,
    ENTITY_FULL_SYNC,
    ENTITY_FIELD_SYNC,
    PLAYER_SECTOR_CHANGE,
    PLAYER_TRANSFER_START,
    PLAYER_TRANSFER_READY,
    PLAYER_TRANSFER_COMPLETE,
    PLAYER_TRANSFER_FAILED,
    CUSTOM
}
